id = "azulejo-brutalism-theme"
name = "Azulejo Brutalism"
version = "1.0.0"
schema_version = 1
authors = ["Łukasz Stachnik"]
description = "Theme inspired by love for Brtualism and Azulejo tilework"
repository = "https://github.com/VerticalHeretic/AzulejoBrutalismTheme"
